version: "3.9"
services:
  web-app:
    build: 
      context: backend
      dockerfile: Dockerfile
    ports:
      - "8000:80"
      - "443:443"
    container_name: "SubscriptionManager"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=N1ghtv1s1on!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/subscriptionmanager.pfx 
    volumes:
      - ./backend/conf.d/https:/https:ro
    depends_on:
      - db 
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    container_name: db
    ports:
      - "1433:1433"
  client:
    build: 
      context: frontend
      dockerfile: Dockerfile
    container_name: client_frontend
    ports: 
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - web-app