version: '3.4'
services: 
  api: 
    build: 
      context: "/backend/SubscriptionManager"
      dockerfile: Dockerfile
    container_name: "api"
    ports: 
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - db
      - db-migrations
    networks:
      - app-network
  db: 
    build:
      context: "/db"
    container_name: "db"
    environment:
      SA_PASSWORD: "subman123"
      ACCEPT_EULA: "Y"
    ports: 
      - "1433:1433"
    networks:
      - app-network
  db-migrations:
    build:
      context: "/db/migrations"
    container_name: "db_migrations"
    volumes: 
      - ./db/migrations:/flyway/sql
    networks:
      - app-network
    depends_on:
      - db
networks:
  app-network:
    driver: bridge